/* Movable Type language lexicon for es localization. */

Lexicon['delete'] = 'borrar';
Lexicon['remove'] = 'borrar';
Lexicon['enable'] = 'habilitar';
Lexicon['disable'] = 'deshabilitar';
Lexicon['delete'] = 'borrar';
Lexicon['You did not select any [_1] to [_2].'] = 'No seleccionó ninguna [_1] sobre la que [_2].';
Lexicon['Are you sure you want to [_2] this [_1]?'] = '¿Está seguro de que desea [_2] esta [_1]?';
Lexicon['Are you sure you want to [_3] the [_1] selected [_2]?'] = '¿Está seguro de que desea [_3] el/los [_1] seleccionado/s [_2]?';
Lexicon['Are you certain you want to remove this role? By doing so you will be taking away the permissions currently assigned to any users and groups associated with this role.'] = '¿Está seguro de que desea borrar este rol? Al hacerlo, eliminará los permisos actualmente asignados a cualquier usuario o grupo relacionados con este rol.';
Lexicon['Are you certain you want to remove these [_1] roles? By doing so you will be taking away the permissions currently assigned to any users and groups associated with these roles.'] = '¿Está seguro de que desea borrar estos [_1] roles? Al hacerlo, eliminará los permisos actualmente asignados a cualquier usuario o grupo relacionados con estos roles.';
Lexicon['enable'] = 'habilitar';
Lexicon['disable'] = 'deshabilitar';
Lexicon['You did not select any [_1] to [_2].'] = 'No seleccionó ninguna [_1] sobre la que [_2].';
Lexicon['Are you sure you want to [_2] this [_1]?'] = '¿Está seguro de que desea [_2] esta [_1]?';
Lexicon['Are you sure you want to [_3] the [_1] selected [_2]?'] = '¿Está seguro de que desea [_3] el/los [_1] seleccionado/s [_2]?';
Lexicon['You did not select any [_1] [_2].'] = 'No seleccionó ninguna [_1] [_2].';
Lexicon['You can only act upon a minimum of [_1] [_2].'] = 'Solo puede actuar sobre un mínimo de [_1] [_2].';
Lexicon['You can only act upon a maximum of [_1] [_2].'] = 'Solo puede actuar sobre un máximo de [_1] [_2].';
Lexicon['You must select an action.'] = 'Debe seleccionar una acción.';
Lexicon['to mark as spam'] = 'para marcar como spam';
Lexicon['to remove spam status'] = 'para desmarcar como spam';
Lexicon['Enter email address:'] = 'Teclee la dirección de correo-e:';
Lexicon['Enter URL:'] = 'Teclee la URL:';
Lexicon['The tag \'[_2]\' already exists. Are you sure you want to merge \'[_1]\' with \'[_2]\'?'] = 'La etiqueta \'[_2]\' ya existe. ¿Está seguro de que desea integrar \'[_1]\' y \'[_2]\'?';
Lexicon['The tag \'[_2]\' already exists. Are you sure you want to merge \'[_1]\' with \'[_2]\' across all weblogs?'] = 'La etiqueta \'[_2]\' ya existe. ¿Está seguro de que desea integrar \'[_1]\' y \'[_2]\' en todos los weblogs?';
Lexicon['Loading...'] = 'Cargando...';
Lexicon['[_1]Publish[_2] your site to see these changes take effect.'] = '[_1]Publique[_2] el sitio para que los cambios tomen efecto.';
Lexicon['[_1]Publish[_2] your site to see these changes take effect.'] = '[_1]Publique[_2] el sitio para que los cambios tomen efecto.';
Lexicon['(None)'] = '(Ninguno)';
Lexicon['Close'] = 'Cerrar';
Lexicon['No Preview Available'] = 'Sin vista previa disponible';
Lexicon['View uploaded file'] = 'Mostrar fichero transferido';
Lexicon['Auto-saving...'] = 'Autoguardado...';
Lexicon['Last auto-save at [_1]:[_2]:[_3]'] = 'Último autoguardado a las [_1]:[_2]:[_3]';
Lexicon['Auto-saving...'] = 'Autoguardado...';
Lexicon['Last auto-save at [_1]:[_2]:[_3]'] = 'Último autoguardado a las [_1]:[_2]:[_3]';
Lexicon['None selected'] = 'Ninguna seleccionada';
Lexicon['Remove'] = 'Borrar';
Lexicon['Remove'] = 'Borrar';
Lexicon['Make primary'] = 'Hacer primario';
Lexicon['Remove'] = 'Borrar';
Lexicon['You have <a href=\'[_3]\'>[quant,_1,comment,comments] from [_2]<\/a>'] = 'Tiene <a href=\'[_3]\'>[quant,_1,comentario,comentarios] de [_2]<\/a>';
Lexicon['You have <a href=\'[_3]\'>[quant,_1,entry,entries] from [_2]<\/a>'] = 'Tiene <a href=\'[_3]\'>[quant,_1,entrada] de [_2]<\/a>';
Lexicon['The tag \'[_2]\' already exists. Are you sure you want to merge \'[_1]\' with \'[_2]\'?'] = 'La etiqueta \'[_2]\' ya existe. ¿Está seguro de que desea integrar \'[_1]\' y \'[_2]\'?';
Lexicon['The tag \'[_2]\' already exists. Are you sure you want to merge \'[_1]\' with \'[_2]\' across all blogs?'] = 'La etiqueta \'[_2]\' ya existe.  ¿Está seguro de querer combinar \'[_1]\' con \'[_2]\' en todos los blogs?';
Lexicon['An error occurred while testing for the new tag name.'] = 'Ocurrió un error mientras se probaba el nuevo nombre de la etiqueta.';
